// <auto-generated />
using System;
using Korp.Estoque.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Korp.Estoque.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    partial class EstoqueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Korp.Estoque.Domain.Entidades.MovimentacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("NotaId")
                        .HasColumnType("uuid")
                        .HasColumnName("nota_id");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ocorrido_em");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("SaldoAnterior")
                        .HasColumnType("integer")
                        .HasColumnName("saldo_anterior");

                    b.Property<int>("SaldoPosterior")
                        .HasColumnType("integer")
                        .HasColumnName("saldo_posterior");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("NotaId")
                        .HasDatabaseName("ix_movimentacoes_nota_id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("movimentacoes_estoque", (string)null);
                });

            modelBuilder.Entity("Korp.Estoque.Domain.Entidades.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("Saldo")
                        .HasColumnType("integer")
                        .HasColumnName("saldo");

                    b.Property<int>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("versao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_codigo");

                    b.ToTable("produtos", null, t =>
                        {
                            t.HasCheckConstraint("ck_produtos_saldo_nao_negativo", "saldo >= 0");
                        });
                });

            modelBuilder.Entity("Korp.Estoque.Domain.Entidades.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Korp.Estoque.Domain.Entidades.Produto", null)
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Korp.Estoque.Domain.Entidades.Produto", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
